#!/usr/bin/env node

// An example hook script to check the commit log message.
// Called by "git commit" with one argument, the name of the file
// that has the commit message.  The hook should exit with non-zero
// status after issuing an appropriate message if it wants to stop the
// commit.  The hook is allowed to edit the commit message file.

try {
	const fs = require('fs')
	const commitMsgFile = process.argv[process.argv.length - 1]
	let commitMsg = fs.readFileSync( commitMsgFile, 'utf8' )
	commitMsg = commitMsg.replace("\"", '\'').replace('\n', '')

	const cmd = `node git-commit-msg-spotify/commit-msg.js "${commitMsg}" "${commitMsgFile}"`
	console.log(cmd)

	require('child_process').exec(
		cmd,
		function (error, stdout) {
			console.log(stdout && stdout);
			if (error !== null) {
				console.log(error);
				process.abort(0);
			}
	  	}
	)

} catch ( e ) {
	console.error(`Unexpected error during commit-msg Git Hook.`)
	console.error(`To disable this, delete or rename .git/hooks/commit-msg`)
	process.exit(1)
}
